import os
import json
import requests

TEAMS_WEBHOOK_URL = os.getenv("TEAMS_WEBHOOK_URL")
REPORT_URL = os.getenv("REPORT_URL", "")

# Load summary JSON (generated by conftest.py)
summary_file = os.path.join("reports", "summary.json")
if os.path.exists(summary_file):
    with open(summary_file, "r") as f:
        summary = json.load(f)
else:
    summary = {"total": "N/A", "passed": "N/A", "failed": "N/A", "skipped": "N/A"}

total = summary["total"]
passed = summary["passed"]
failed = summary["failed"]
skipped = summary["skipped"]

summary_text = (
    f"**Test Automation Summary**\n\n"
    f"- Total Tests: {total}\n"
    f"- ✅ Passed: {passed}\n"
    f"- ❌ Failed: {failed}\n"
    f"- ⚠️ Skipped: {skipped}\n\n"
    f"[📂 View Detailed Report]({REPORT_URL})"
)

payload = {
    "@type": "MessageCard",
    "@context": "https://schema.org/extensions",
    "summary": "Automation Test Summary",
    "themeColor": "0076D7" if failed == 0 else "FF0000",
    "title": "🚀 Automation Test Summary",
    "text": summary_text,
}

if TEAMS_WEBHOOK_URL:
    resp = requests.post(TEAMS_WEBHOOK_URL, json=payload)
    if resp.status_code != 200:
        print(f"❌ Teams webhook failed: {resp.text}")
    else:
        print("✅ Test summary sent to Teams successfully.")
else:
    print("⚠️ TEAMS_WEBHOOK_URL not set")
